name: Tests

on:
  - pull_request
  - push

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26'

      - name: Git checkout
        uses: actions/checkout@v7

      - name: go fmt
        run: |
          unformatted=$(gofmt -l .)
          if [ -n "$unformatted" ]; then
              echo "The following files are not formatted:"
              gofmt -d .
              exit 1
          fi

      - name: go testing
        run: |
          go mod tidy
          go vet ./...
          go test -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: atbore-phx/sbam

      - name: Build
        run: make build
